load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "SortLib",
    srcs = ["sortset.cc"],
    hdrs = ["sortset.h"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_google_glog//:glog",
    ],
)
